FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app

# Копируем все POM файлы
COPY . .

# Сначала загружаем зависимости родительского POM
RUN mvn dependency:go-offline -N


# Собираем только showcase модуль
RUN mvn clean package -DskipTests -pl showcase -am

FROM eclipse-temurin:21-jre-alpine
COPY --from=builder /app/showcase/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]