# Этап сборки
FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app

# Копируем все POM файлы
COPY . .

# Сначала устанавливаем родительский POM (без сборки модулей)
RUN mvn install -N -DskipTests

# Собираем ТОЛЬКО wallet модуль
RUN mvn clean package -DskipTests -pl wallet

# Этап запуска
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/wallet/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]