CREATE TABLE users
(
    id       BIGSERIAL    NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(50)  NOT NULL DEFAULT 'ROLE_USER',

    CONSTRAINT users_pk PRIMARY KEY (id)
);

ALTER TABLE orders ADD COLUMN user_id BIGINT;
