spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:market
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.yaml
