spring:
  application:
    name: my-market-app
  config:
    import:
      - classpath:application-db.yml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cache:
    redis:
      time-to-live: 60000