spring:
  application:
    name: my-market-app
  config:
    import:
      - classpath:application-db.yml
  data:
    redis:
      host: market-redis-1
      port: 6379
  cache:
    redis:
      time-to-live: 60000

webservers:
  wallet:
    host: http://market-wallet-1:8081