server:
  port: 8081

spring:
  application:
    name: payment-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/payment
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.yaml
    url: jdbc:postgresql://localhost:5432/payment
    user: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
